# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: docker-hub-connection
        
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        dockerFile: '**/Dockerfile'
        repository: 3939/go-app
        tags: |
          $(tag)
          
    - script: |
        cid=$(docker run -d --name ipfs-node -p 8080:8080 -p 4001:4001 -p 127.0.0.1:5001:5001 3939/go-app:$(tag))
        echo $cid
        output=$(docker exec $cid ipfs add /export/main)
        echo $output
        
        
