# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger:
- master

parameters:
- name: param1
  type: string
  default: value1
  
- name: param2
  type: string
  default: value2
  
- name: param3
  type: string
  default: value3

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
#    - task: Docker@2
#      displayName: Login to Docker Hub
#      inputs:
#        command: login
#        containerRegistry: docker-hub-connection
#        
#    - task: Docker@2
#      displayName: Build and Push
#      inputs:
#        command: buildAndPush
#        dockerFile: '**/Dockerfile'
#        repository: 3939/go-app
#        tags: |
#          $(tag)
#          
#    - script: |
#        cid=$(docker run -d --name ipfs-node -p 8080:8080 -p 4001:4001 -p 127.0.0.1:5001:5001 3939/go-app:$(tag))
#        echo $cid
#        output=$(docker exec $cid ipfs add /export/main)
#        echo $output
        
    - script: |
        cat << EOF > vars.yml
        ---
        param1: ${{ parameters.param1 }}
        param2: ${{ parameters.param2 }}
        param3: ${{ parameters.param3 }}
        EOF
        
    - script: |
        pip install shyaml -y
        param1=$(cat vars.yml | shyaml get-value param1)
        echo $param1 > param1.txt
        
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifactName: 'drop'



        
        
        
